sudo: required
language: node_js
node_js:
  - 6
  - 7
  - node
cache:
  directories:
    - node_modules
install:
  - npm i -g yarn && yarn
  - npm i -g webpack
  - yarn install
script:
  - yarn run build